inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Documentation:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 300

MethodParameterName:
  Enabled: false

UselessMethodDefinition:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Metrics/AbcSize:
  Max: 300

EmptyLines:
  Enabled: false

CommentIndentation:
  Enabled: false

RedundantPresenceValidationOnBelongsTo:
  Enabled: false

InverseOf:
  Enabled: false
